Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

  UploadSavePath: storage/uploads # 上传文件的最终保存目录
  UploadServerUrl: http://127.0.0.1:8000/static # 上传文件后的用于展示的文件服务地址
  UploadImageMaxSize: 5  # MB # 上传文件所允许的最大空间大小（MB）
  UploadImageAllowExts: # 上传文件所允许的文件后缀
    - .jpg
    - .jpeg
    - .png

Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: admin123  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: go-tour
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

JWT:
  Secret: xiaohuaye # 不能暴露给外部
  Issuer: blog-server # 签发者
  Expire: 7200